/**
  ******************************************************************************
  * @file    main.c
  * @brief   EL05 Motor Control Example
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "can.h"
#include "el05_motor.h"
#include <stdio.h>

/* Private variables ---------------------------------------------------------*/
CAN_HandleTypeDef hcan1;

// Motor handle
EL05_MotorHandle_t motor1;

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
    /* MCU Configuration--------------------------------------------------------*/
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_CAN1_Init();

    /* Initialize EL05 motor driver */
    EL05_Init(&hcan1);

    /* Start CAN reception */
    if (EL05_StartReception() != HAL_OK) {
        Error_Handler();
    }

    /* Configure motor */
    motor1.can_id = 0x01;  // Set motor CAN ID (default is 0x01)
    motor1.mode = EL05_MODE_MIT;  // Default mode
    motor1.state = EL05_STATE_DISABLE;
    motor1.is_online = 0;

    /* Enable motor */
    if (EL05_Enable(&motor1) != HAL_OK) {
        Error_Handler();
    }

    HAL_Delay(100);  // Wait for motor to initialize

    /* Infinite loop */
    while (1)
    {
        /* Example 1: MIT Mode Control (运控模式) */
        #if 0
        EL05_MitControl_t mit_cmd;
        mit_cmd.p_des = 0.0f;   // Target position (rad)
        mit_cmd.v_des = 1.0f;   // Target velocity (rad/s)
        mit_cmd.kp = 10.0f;     // Position gain
        mit_cmd.kd = 0.5f;      // Velocity gain
        mit_cmd.t_ff = 0.0f;    // Feedforward torque (N·m)

        EL05_MitControl(&motor1, &mit_cmd);
        HAL_Delay(10);  // 100Hz control rate
        #endif

        /* Example 2: Position Control (CSP Mode) */
        #if 0
        float target_position = 3.14f;  // Target position (rad)
        float velocity_limit = 5.0f;    // Velocity limit (rad/s)

        EL05_PositionControl(&motor1, target_position, velocity_limit);
        HAL_Delay(100);  // 10Hz control rate
        #endif

        /* Example 3: Velocity Control */
        #if 0
        float target_velocity = 2.0f;   // Target velocity (rad/s)
        float current_limit = 5.0f;     // Current limit (A)

        EL05_VelocityControl(&motor1, target_velocity, current_limit);
        HAL_Delay(100);  // 10Hz control rate
        #endif

        /* Example 4: Current Control */
        #if 0
        float target_current = 1.0f;  // Target current (A)

        EL05_CurrentControl(&motor1, target_current);
        HAL_Delay(100);  // 10Hz control rate
        #endif

        /* Example 5: Check Motor Status */
        #if 1
        // Check if motor is online (timeout 100ms)
        if (EL05_CheckOnline(&motor1, 100)) {
            // Motor is online, get feedback
            EL05_MotorFeedback_t *feedback = EL05_GetFeedback(&motor1);

            // Use feedback data
            // float position = feedback->position;
            // float velocity = feedback->velocity;
            // float torque = feedback->torque;
        } else {
            // Motor is offline, handle error
        }

        HAL_Delay(10);
        #endif

        /* Example 6: Sinusoidal Motion Test */
        #if 0
        static float time = 0.0f;
        float amplitude = 3.0f;      // Amplitude (rad)
        float frequency = 0.5f;      // Frequency (Hz)
        float position = amplitude * sinf(2.0f * 3.14159f * frequency * time);

        EL05_PositionControl(&motor1, position, 10.0f);

        time += 0.01f;  // Increment time (10ms)
        HAL_Delay(10);
        #endif
    }
}

/**
  * @brief  CAN RX0 Interrupt Callback
  * @param  hcan: pointer to a CAN_HandleTypeDef structure that contains
  *         the configuration information for the specified CAN.
  * @retval None
  */
void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan)
{
    // Call EL05 motor RX callback
    EL05_CAN_RxCallback(hcan);
}

/**
  * @brief  CAN RX1 Interrupt Callback
  * @param  hcan: pointer to a CAN_HandleTypeDef structure that contains
  *         the configuration information for the specified CAN.
  * @retval None
  */
void HAL_CAN_RxFifo1MsgPendingCallback(CAN_HandleTypeDef *hcan)
{
    // Call EL05 motor RX callback
    EL05_CAN_RxCallback(hcan);
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
    // This function is generated by CubeMX
    // Keep the original implementation
}

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
    /* User can add his own implementation to report the HAL error return state */
    __disable_irq();
    while (1)
    {
    }
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
    /* User can add his own implementation to report the file name and line number,
       ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
}
#endif /* USE_FULL_ASSERT */
