/**
  ******************************************************************************
  * @file    nrf24l01_rx_example.c
  * @brief   NRF24L01+ Receiver Usage Examples
  * @note    Shows how to integrate receiver with motor control
  *
  * @author  Mingyue Class 2026
  * @date    2026-04-25
  ******************************************************************************
  */

#include "nrf24l01_rx.h"
#include "main.h"

/* ============================================================================
 *                          EXAMPLE 1: BASIC USAGE
 * ============================================================================ */

/**
 * @brief Basic receiver initialization and data reading
 */
void NRF24L01_RX_Basic_Example(void)
{
    // Initialize NRF24L01 receiver
    NRF24L01_RX_Init();

    // Wait for pairing with remote (timeout 10 seconds)
    if (!NRF24L01_RX_WaitForPairing()) {
        printf("Pairing failed! Check remote controller.\n");
        return;
    }
    printf("Paired successfully!\n");

    while (1) {
        // Check and read data
        if (NRF24L01_RX_ReadData()) {
            // Get parsed data
            RemoteControlData_t *rc_data = NRF24L01_RX_GetData();

            // Use the data (joystick values: 128=center, <128=left/forward, >128=right/backward)
            uint8_t right_x = rc_data->right_joystick_x;
            uint8_t right_y = rc_data->right_joystick_y;
            uint8_t left_x = rc_data->left_joystick_x;
            uint8_t left_y = rc_data->left_joystick_y;
            uint8_t button = rc_data->button_state;

            // Example: Print to debug
            printf("RX:%d RY:%d LX:%d LY:%d BTN:0x%02X\n",
                   right_x, right_y, left_x, left_y, button);
        }

        HAL_Delay(10); // 100Hz check rate
    }
}

/* ============================================================================
 *                          EXAMPLE 2: INTEGRATION WITH MAIN.C
 * ============================================================================ */

/**
 * @brief Add this to main.c
 *
 * Step 1: Include header
 *   #include "nrf24l01_rx.h"
 *
 * Step 2: Initialize in main() after system init
 *   NRF24L01_RX_Init();
 *   if (!NRF24L01_RX_WaitForPairing()) {
 *       Error_Handler();
 *   }
 *
 * Step 3: Add to main loop
 *   if (NRF24L01_RX_ReadData()) {
 *       RemoteControlData_t *rc = NRF24L01_RX_GetData();
 *       // Process joystick values: rc->right_joystick_x/y, rc->left_joystick_x/y
 *       // Process button state: rc->button_state
 *   }
 */

/**
 * @brief Complete main.c example
 */
void main_example(void)
{
    // System initialization (generated by CubeMX)
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_SPI3_Init(); // Make sure SPI3 is initialized

    // Initialize NRF24L01 receiver
    NRF24L01_RX_Init();

    // Wait for pairing with remote controller
    printf("Waiting for pairing...\n");
    if (!NRF24L01_RX_WaitForPairing()) {
        printf("Pairing failed!\n");
        Error_Handler();
    }
    printf("Paired successfully!\n");

    // Main loop
    while (1) {
        // Read remote control data
        if (NRF24L01_RX_ReadData()) {
            RemoteControlData_t *rc = NRF24L01_RX_GetData();

            // Check if data is valid
            if (rc->data_valid) {
                // Convert joystick values to motor commands
                // Joystick: 128=center, <128=left/forward, >128=right/backward
                int right_x = (int)rc->right_joystick_x - 128;  // -128 to 127
                int right_y = (int)rc->right_joystick_y - 128;
                int left_x = (int)rc->left_joystick_x - 128;
                int left_y = (int)rc->left_joystick_y - 128;

                // Convert to motor speeds (example: tank drive)
                int left_motor = left_y;   // Forward/backward on left joystick
                int right_motor = right_y; // Forward/backward on right joystick

                // Example: Control EL05 motors
                // float left_vel = left_motor * 0.1f;  // Convert to rad/s
                // float right_vel = right_motor * 0.1f;
                // EL05_VelocityControl(&motor_left, left_vel, 5.0f);
                // EL05_VelocityControl(&motor_right, right_vel, 5.0f);

                // Handle button commands
                if (rc->button_state & 0x01) {
                    // KEY1 pressed: Enable motors
                    // EL05_Enable(&motor_left);
                    // EL05_Enable(&motor_right);
                }
                if (rc->button_state & 0x02) {
                    // KEY2 pressed: Disable motors
                    // EL05_Disable(&motor_left);
                    // EL05_Disable(&motor_right);
                }
            }
        }

        // Check if remote is still online
        if (!NRF24L01_RX_IsOnline()) {
            // No data received for 500ms - stop motors for safety
            // EL05_Disable(&motor_left);
            // EL05_Disable(&motor_right);
        }

        HAL_Delay(10); // 100Hz control loop
    }
}

/* ============================================================================
 *                          EXAMPLE 3: MOTOR CONTROL INTEGRATION
 * ============================================================================ */

/**
 * @brief Apply remote control to EL05 motors
 */
void ApplyRemoteControlToMotors(void)
{
    static uint8_t motors_enabled = 0;

    // Read remote data
    if (NRF24L01_RX_ReadData()) {
        RemoteControlData_t *rc = NRF24L01_RX_GetData();

        if (rc->data_valid) {
            // Convert joystick values to motor speeds
            // Joystick: 128=center, convert to -128~127 range
            int right_y = (int)rc->right_joystick_y - 128;
            int left_y = (int)rc->left_joystick_y - 128;

            // Convert to rad/s
            float left_vel = left_y * 0.1f;   // Scale factor
            float right_vel = right_y * 0.1f;

            // EL05 motor handles (adjust CAN IDs as needed)
            // EL05_MotorHandle_t motor_left = {.can_id = 0x01};
            // EL05_MotorHandle_t motor_right = {.can_id = 0x02};

            // Check button state
            if (rc->button_state & 0x01) {
                // KEY1: Enable motors
                if (!motors_enabled) {
                    // EL05_Enable(&motor_left);
                    // EL05_Enable(&motor_right);
                    motors_enabled = 1;
                    HAL_Delay(100); // Wait for enable
                }
            } else if (rc->button_state & 0x02) {
                // KEY2: Disable motors
                // EL05_Disable(&motor_left);
                // EL05_Disable(&motor_right);
                motors_enabled = 0;
            }

            // Apply velocity control if motors are enabled
            if (motors_enabled) {
                // EL05_VelocityControl(&motor_left, left_vel, 5.0f);
                // EL05_VelocityControl(&motor_right, right_vel, 5.0f);
            }
        }
    }

    // Safety: Stop motors if remote is offline
    if (!NRF24L01_RX_IsOnline()) {
        // EL05_Disable(&motor_left);
        // EL05_Disable(&motor_right);
        motors_enabled = 0;
    }
}

/* ============================================================================
 *                          EXAMPLE 4: M0601C MOTOR INTEGRATION
 * ============================================================================ */

/**
 * @brief Apply remote control to M0601C motors (UART)
 */
void ApplyRemoteControlToM0601C(void)
{
    // Read remote data
    if (NRF24L01_RX_ReadData()) {
        RemoteControlData_t *rc = NRF24L01_RX_GetData();

        if (rc->data_valid) {
            // Convert joystick values to RPM
            int right_y = (int)rc->right_joystick_y - 128;
            int left_y = (int)rc->left_joystick_y - 128;

            int left_rpm = left_y * 2;   // Scale: -256 to 254 RPM
            int right_rpm = right_y * 2;

            // Send to M0601C motors (ID 1 and 2)
            // MOTOR_SetSpeed(1, left_rpm);
            // MOTOR_SetSpeed(2, right_rpm);

            // Handle buttons
            if (rc->button_state & 0x01) {
                // KEY1: Start motors
            }
            if (rc->button_state & 0x02) {
                // KEY2: Stop motors
                // MOTOR_Stop(1);
                // MOTOR_Stop(2);
            }
        }
    }

    // Safety stop
    if (!NRF24L01_RX_IsOnline()) {
        // MOTOR_Stop(1);
        // MOTOR_Stop(2);
    }
}

/* ============================================================================
 *                          EXAMPLE 5: CUSTOM DATA PROCESSING
 * ============================================================================ */

/**
 * @brief Process custom data format
 * @note  Modify this if your transmitter sends different data format
 */
void ProcessCustomData(void)
{
    if (NRF24L01_RX_ReadData()) {
        RemoteControlData_t *rc = NRF24L01_RX_GetData();

        // Convert joystick values to centered range
        int right_y = (int)rc->right_joystick_y - 128;
        int left_y = (int)rc->left_joystick_y - 128;

        // Example: Dead zone filtering
        if (abs(right_y) < 10) {
            right_y = 0;
        }
        if (abs(left_y) < 10) {
            left_y = 0;
        }

        // Example: Exponential mapping for smoother control
        float left_exp = (left_y > 0) ?
            (left_y * left_y / 128.0f) :
            -(left_y * left_y / 128.0f);
        float right_exp = (right_y > 0) ?
            (right_y * right_y / 128.0f) :
            -(right_y * right_y / 128.0f);

        // Apply to motors
        // EL05_VelocityControl(&motor_left, left_exp * 0.1f, 5.0f);
        // EL05_VelocityControl(&motor_right, right_exp * 0.1f, 5.0f);
    }
}

/* ============================================================================
 *                          EXAMPLE 6: STATUS MONITORING
 * ============================================================================ */

/**
 * @brief Monitor receiver status
 */
void MonitorReceiverStatus(void)
{
    static uint32_t last_print_time = 0;

    // Print status every 1 second
    if (HAL_GetTick() - last_print_time >= 1000) {
        last_print_time = HAL_GetTick();

        if (NRF24L01_RX_IsOnline()) {
            RemoteControlData_t *rc = NRF24L01_RX_GetData();
            printf("Remote Online - RX:%d RY:%d LX:%d LY:%d BTN:0x%02X\n",
                   rc->right_joystick_x, rc->right_joystick_y,
                   rc->left_joystick_x, rc->left_joystick_y,
                   rc->button_state);
        } else {
            printf("Remote Offline!\n");
        }
    }
}

/* ============================================================================
 *                          STM32CUBEMX CONFIGURATION
 * ============================================================================ */

/**
 * @brief STM32CubeMX Configuration Guide
 *
 * 1. SPI3 Configuration:
 *    - Connectivity -> SPI3
 *    - Mode: Full-Duplex Master
 *    - Clock Polarity: Low
 *    - Clock Phase: 1 Edge
 *    - Prescaler: 16
 *    - Pins: PC10(SCK), PC11(MISO), PC12(MOSI)
 *
 * 2. GPIO Configuration:
 *    - PC8: GPIO_Output (CE)
 *    - PC9: GPIO_Output (CSN)
 *    - PC7: GPIO_Input (IRQ, optional)
 *
 * 3. Add to main.c:
 *    - Include: #include "nrf24l01_rx.h"
 *    - After MX_SPI3_Init(): NRF24L01_RX_Init();
 *    - In main loop: if (NRF24L01_RX_ReadData()) { ... }
 */
